name = "Geodynamics"
uuid = "bc6a81d0-73d8-4281-aded-9a5001dee72a"
version = "0.1.0"
authors = ["EarthSciML authors and contributors"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
EarthSciMLBase = "e53f1632-a13c-4728-9402-0c66d48804b0"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
DocStringExtensions = "0.9.5"
DynamicQuantities = "1"
EarthSciMLBase = "0.24"
ModelingToolkit = "10"
OrdinaryDiffEqDefault = "1"
SciMLBase = "2"
Test = "1"
TestItemRunner = "1.1.0"
julia = "1.10"

[extras]
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "OrdinaryDiffEqDefault", "SciMLBase", "TestItemRunner"]
