[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
EarthSciMLBase = "e53f1632-a13c-4728-9402-0c66d48804b0"
Geodynamics = "bc6a81d0-73d8-4281-aded-9a5001dee72a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
Documenter = "1"
DynamicQuantities = "1"
EarthSciMLBase = "0.24"
ModelingToolkit = "10"
